parser: "@typescript-eslint/parser"
plugins:
    - "@typescript-eslint"
parserOptions:
    ecmaVersion: latest
    sourceType: module
env:
    node: true
    es6: true
    commonjs: true
extends:
    - eslint:recommended
    - plugin:@typescript-eslint/recommended
    - plugin:import/recommended
    - plugin:import/errors
    - plugin:import/warnings
    - plugin:import/typescript
rules:
    quotes:
        - error
        - double
    object-curly-spacing:
        - error
        - always
    "@typescript-eslint/no-explicit-any": "off"
ignorePatterns:
    - dist
    - "*.md"
