include:
    - db.yml

services:
    kaikibot:
        depends_on:
            - db
        links:
            - db
        ports:
            - "6363:6363"
        build:
            context: .
            dockerfile: Dockerfile.dev
            network: host
            args:
                - DATABASE_URL=$DATABASE_URL_DOCKER_BUILD
        restart: unless-stopped
        env_file: ./.env
        stdin_open: true
        tty: true
        volumes:
            - ./src:/usr/app/src
